# CẤP 1: CÁC BƯỚC THỰC THI
steps:
  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-node-service:$COMMIT_SHA'
      - '.'

  # 2. Push image lên Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-node-service:$COMMIT_SHA'

  # 3. Deploy image đó lên Cloud Run
  - name: 'gcr.io/google/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-node-service' # Tên dịch vụ Cloud Run
      - '--image=asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-node-service:$COMMIT_SHA'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--quiet'

# CẤP 1: KHAI BÁO THÀNH QUẢ IMAGE (ngang hàng với steps)
images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-node-service:$COMMIT_SHA'

# CẤP 1: CÁC TÙY CHỌN BUILD (ngang hàng với steps)
# <--- PHẦN SỬA LỖI NẰM Ở ĐÂY
options:
  logging: CLOUD_LOGGING_ONLY
