steps:
# 1. Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  # Đổi tên image/repo theo ý bạn
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-node-service:$COMMIT_SHA'
  # Dấu "." này có nghĩa là build từ thư mục gốc,
  # sử dụng Dockerfile ở gốc
  - '.' 

# 2. Push image lên Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-node-service:$COMMIT_SHA'

# 3. Deploy image đó lên Cloud Run
- name: 'gcr.io/google/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'my-node-service' # Tên dịch vụ Cloud Run
  - '--image=asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-node-service:$COMMIT_SHA'
  - '--region=asia-southeast1' # Đổi region nếu cần
  - '--platform=managed'
  - '--allow-unauthenticated'
  - '--quiet'

  options:
  logging: CLOUD_LOGGING_ONLY
