import db from '../config/db.js';
import RestaurantDAO from '../dao/RestaurantDAO.js';
// static async createRestaurant({
//     restaurantPartnerID,
//     name,
//     description,
//     address: addr,
//     thumbnailURL,
//     status,
//   }) {
//     return await sequelize.transaction(async (t) => {
//       const a = await address.create({
//         number: addr.number,
//         street: addr.street,
//         ward: addr.ward,
//         // fullAddress could be generated by a trigger; leave null if DB handles it
//       }, { transaction: t });

//       const r = await restaurant.create({
//         restaurantPartnerID,
//         name,
//         description,
//         addressID: a.addressID,
//         thumbnailURL,
//         status: status ?? true,
//       }, { transaction: t });

//       return {
//         restaurantID: r.restaurantID,
//         restaurantPartnerID: r.restaurantPartnerID,
//         name: r.name,
//         description: r.description,
//         hallCount: r.hallCount ?? 0,
//         addressID: r.addressID,
//         thumbnailURL: r.thumbnailURL,
//         status: r.status,
//       };
//     });
//   }
const data = {
    restaurantPartnerID: 2,
    name: "Test Restaurant",
    description: "A restaurant created for testing purposes",
    address: {
        number: "123",
        street: "Test Street",
        ward: "Test Ward"
    },
    thumbnailURL: "http://example.com/thumbnail.jpg",
    status: true
};
;(async () => {
  try {
    // Kết nối Sequelize (verify)
    await db.sequelize.authenticate();
    console.log('Sequelize connected');

    const restaurant = await RestaurantDAO.getAll();
    console.log('restaurant:', JSON.stringify(restaurant, null, 2));
  } catch (err) {
    console.error('Test failed:', err);
  } finally {
    // Đóng kết nối (nếu cần)
    await db.sequelize.close();
    process.exit(0);
  }
})();